INSERT INTO BLOGGER (NAME, BIRTH_DATE) VALUES('Legen-daaary', '2002-03-26');
INSERT INTO ENTRY (TITLE, CONTENT, POSTED, BLOGGER_ID)
    VALUES('FABULOUS!', 'First entry using JPA!', CURRENT_TIMESTAMP, (SELECT ID FROM BLOGGER WHERE NAME = 'Legen-daaary'));

INSERT INTO BLOGGER (NAME, BIRTH_DATE) VALUES('Admin', '2000-01-01');
INSERT INTO ENTRY (TITLE, CONTENT, POSTED, BLOGGER_ID)
    VALUES('Admin entry', 'Admin on board :P', CURRENT_TIMESTAMP, (SELECT ID FROM BLOGGER WHERE NAME = 'Admin'));